package View;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public LandingPage() {
        setAlwaysOnTop(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        btlogin = new javax.swing.JButton();
        btsignup = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        judul1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul1.setText("Selamat Datang");
        getContentPane().add(judul1);
        judul1.setBounds(130, 130, 310, 50);

        judul2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul2.setText("di Aplikasi Rental Mobil");
        getContentPane().add(judul2);
        judul2.setBounds(130, 180, 420, 50);

        judul3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul3.setText("RTHR33");
        getContentPane().add(judul3);
        judul3.setBounds(130, 230, 420, 50);

        btlogin.setBackground(new java.awt.Color(255, 153, 153));
        btlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btlogin.setForeground(new java.awt.Color(255, 255, 255));
        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        getContentPane().add(btlogin);
        btlogin.setBounds(780, 300, 170, 50);

        btsignup.setBackground(new java.awt.Color(255, 153, 153));
        btsignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btsignup.setForeground(new java.awt.Color(255, 255, 255));
        btsignup.setText("Sign Up");
        btsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btsignup);
        btsignup.setBounds(780, 380, 170, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Entity/sign in (1).png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1280, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        Login lg = new Login();
        lg.setSize(1181, 700);
        lg.setResizable(false);
        lg.setVisible(true);
        lg.setExtendedState(JFrame.NORMAL);
        this.dispose();
    }//GEN-LAST:event_btloginActionPerformed

    private void btsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsignupActionPerformed
        Register rg = new Register();
        rg.setSize(1181, 700);
        rg.setResizable(false);
        rg.setVisible(true);
        rg.setExtendedState(JFrame.NORMAL);
        this.dispose();
    }//GEN-LAST:event_btsignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    public static boolean authenticate(String nik, String password) {
        Connection conn = null;
        boolean authenticated = false;
        try {
            String url = "jdbc:mysql://localhost:3306/dbrental";
            String rg = "root";
            String pass = "";
            conn = DriverManager.getConnection(url, rg, pass);

            String sql = "SELECT * FROM tbrg WHERE NIK = ? AND passwordUser = ?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, nik);
            preparedStatement.setString(2, password);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                authenticated = true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
        return authenticated;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btlogin;
    private javax.swing.JButton btsignup;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    // End of variables declaration//GEN-END:variables
}
