package View;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import java.sql.SQLException;
import javax.swing.JFrame;

public class Login extends javax.swing.JFrame {

    private JComboBox<String> userRole;

    /**
     * Creates new form Register
     */
    public Login() {
        setAlwaysOnTop(false);
        initComponents();
        combobox();
    }

    private void combobox() {
        // Create JComboBox
        userRole = new JComboBox<>();

        // Add items to JComboBox
        userRole.addItem("Pemilik");
        userRole.addItem("Pelanggan");
    }

    ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NIK = new javax.swing.JLabel();
        pw = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btlogin = new javax.swing.JButton();
        masuk = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        NIK1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NIK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NIK.setForeground(new java.awt.Color(255, 153, 153));
        NIK.setText("Sebagai");
        getContentPane().add(NIK);
        NIK.setBounds(710, 190, 80, 25);

        pw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pw.setForeground(new java.awt.Color(255, 153, 153));
        pw.setText("Password");
        getContentPane().add(pw);
        pw.setBounds(710, 400, 110, 25);

        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });
        getContentPane().add(txtnik);
        txtnik.setBounds(710, 340, 320, 40);

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword);
        txtpassword.setBounds(710, 440, 320, 40);

        btlogin.setBackground(new java.awt.Color(255, 153, 153));
        btlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btlogin.setForeground(new java.awt.Color(255, 255, 255));
        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        getContentPane().add(btlogin);
        btlogin.setBounds(790, 540, 170, 50);

        masuk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        masuk.setForeground(new java.awt.Color(255, 153, 153));
        masuk.setText("Masuk");
        getContentPane().add(masuk);
        masuk.setBounds(830, 120, 80, 30);

        judul1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul1.setText("Selamat Datang");
        getContentPane().add(judul1);
        judul1.setBounds(130, 130, 310, 50);

        judul2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul2.setText("di Aplikasi Rental Mobil");
        getContentPane().add(judul2);
        judul2.setBounds(130, 180, 420, 50);

        judul3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul3.setText("RTHR33");
        getContentPane().add(judul3);
        judul3.setBounds(130, 230, 420, 50);

        NIK1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NIK1.setForeground(new java.awt.Color(255, 153, 153));
        NIK1.setText("NIK");
        getContentPane().add(NIK1);
        NIK1.setBounds(710, 300, 50, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemilik", "Pelanggan" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(710, 230, 320, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Entity/sign in (1).png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1280, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        String nik = txtnik.getText();
        String password = new String(txtpassword.getPassword());

        // Mendapatkan peran pengguna dari JComboBox
        String role = (String) jComboBox1.getSelectedItem();

        if (authenticate(nik, password, role)) {
            JOptionPane.showMessageDialog(null, "Login Successful!");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid NIK or Password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean authenticate(String nik, String password, String role) {
        Connection conn = null;
        boolean authenticated = false;
        try {
            String url = "jdbc:mysql://localhost:3306/dbrental";
            String user = "root";
            String pass = "";
            conn = DriverManager.getConnection(url, user, pass);

            String sql = "";
            if (role.equals("Pelanggan")) {
                sql = "SELECT * FROM tbuser WHERE NIK = ? AND passwordUser = ?";
            } else if (role.equals("Pemilik")) {
                sql = "SELECT * FROM tbadmin WHERE NIK = ? AND password = ?";
            }

            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, nik);
            preparedStatement.setString(2, password);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                authenticated = true;
                // Redirect to appropriate frame based on user role
                if (role.equals("Pelanggan")) {
                    Transaksi tr = new Transaksi();
                    tr.setSize(1181, 700);
                    tr.setResizable(false);
                    tr.setVisible(true);
                    tr.setExtendedState(JFrame.NORMAL);
                    this.dispose();
                } else if (role.equals("Pemilik")) {
                    UserManagement um = new UserManagement();
                    um.setSize(1181, 700);
                    um.setResizable(false);
                    um.setVisible(true);
                    um.setExtendedState(JFrame.NORMAL);
                    this.dispose();
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
        return authenticated;

    }//GEN-LAST:event_btloginActionPerformed

    public static void main(String atrs[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public boolean authenticate(String nik, String password) {
        Connection conn = null;
        boolean authenticated = false;
        try {
            String url = "jdbc:mysql://localhost:3306/dbrental";
            String user = "root";
            String pass = "";
            conn = DriverManager.getConnection(url, user, pass);

            String sql = "SELECT * FROM tbuser WHERE NIK = ? AND passwordUser = ?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, nik);
            preparedStatement.setString(2, password);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                authenticated = true;
                if ("Pelanggan".equals((String) jComboBox1.getSelectedItem())) {
                    Transaksi tr = new Transaksi();
                    tr.setSize(1181, 700);
                    tr.setResizable(false);
                    tr.setVisible(true);
                    tr.setExtendedState(JFrame.NORMAL);
                    this.dispose();
                } else if ("Pemilik".equals((String) jComboBox1.getSelectedItem())) {
                    UserManagement um = new UserManagement();
                    um.setSize(1181, 700);
                    um.setResizable(false);
                    um.setVisible(true);
                    um.setExtendedState(JFrame.NORMAL);
                    this.dispose();
                }

            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
        return authenticated;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NIK;
    private javax.swing.JLabel NIK1;
    private javax.swing.JLabel background;
    private javax.swing.JButton btlogin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel masuk;
    private javax.swing.JLabel pw;
    private javax.swing.JTextField txtnik;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
