package View;

import Entity.Koneksi;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Asus
 */
public class UserManagement extends javax.swing.JFrame {

    private Statement stm;
    private ResultSet res;

    /**
     * Creates new form Register
     */
    public UserManagement() {
        initComponents();
        setAlwaysOnTop(false);
        try {

            Connection connection = Koneksi.getConnection();
            stm = connection.createStatement();

            tampiltabel();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void tampiltabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama User");
        model.addColumn("No HP User");
        model.addColumn("Password User");

        TableUser.setModel(model);
        try {
            Connection connection = Koneksi.getConnection();
            res = stm.executeQuery("SELECT NIK, namaUser, nohpUser, passwordUser FROM tbuser");
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("NIK"),
                    res.getString("namaUser"),
                    res.getString("nohpUser"),
                    res.getString("passwordUser"),
     
                });

            }
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NIK = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        nohp = new javax.swing.JLabel();
        txtnohp = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        txtpw = new javax.swing.JPasswordField();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        btkelolauser = new javax.swing.JButton();
        btkelolamobil = new javax.swing.JButton();
        btkelolatransaksi = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NIK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NIK.setText("NIK");
        getContentPane().add(NIK);
        NIK.setBounds(370, 140, 180, 25);

        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });
        getContentPane().add(txtnik);
        txtnik.setBounds(370, 180, 320, 40);

        nama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nama.setText("Nama");
        getContentPane().add(nama);
        nama.setBounds(370, 240, 70, 25);

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama);
        txtnama.setBounds(370, 280, 320, 40);

        nohp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nohp.setText("Nomor Handphone");
        getContentPane().add(nohp);
        nohp.setBounds(760, 140, 180, 25);

        txtnohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnohpActionPerformed(evt);
            }
        });
        getContentPane().add(txtnohp);
        txtnohp.setBounds(760, 180, 320, 40);

        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setText("Password");
        getContentPane().add(password);
        password.setBounds(760, 240, 110, 25);

        txtpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwActionPerformed(evt);
            }
        });
        getContentPane().add(txtpw);
        txtpw.setBounds(760, 280, 320, 40);

        bthapus.setBackground(new java.awt.Color(255, 153, 153));
        bthapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bthapus.setForeground(new java.awt.Color(255, 255, 255));
        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus);
        bthapus.setBounds(920, 370, 170, 50);

        bttambah.setBackground(new java.awt.Color(255, 153, 153));
        bttambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttambah.setForeground(new java.awt.Color(255, 255, 255));
        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        getContentPane().add(bttambah);
        bttambah.setBounds(360, 370, 170, 50);

        btedit.setBackground(new java.awt.Color(255, 153, 153));
        btedit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btedit.setForeground(new java.awt.Color(255, 255, 255));
        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit);
        btedit.setBounds(650, 370, 170, 50);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(32769, 32769));

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Nomor Handphone", "Password"
            }
        ));
        jScrollPane1.setViewportView(TableUser);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 490, 920, 210);

        btkelolauser.setBackground(new java.awt.Color(255, 102, 153));
        btkelolauser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btkelolauser.setForeground(new java.awt.Color(255, 255, 255));
        btkelolauser.setText("Kelola Data User");
        btkelolauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkelolauserActionPerformed(evt);
            }
        });
        getContentPane().add(btkelolauser);
        btkelolauser.setBounds(20, 140, 210, 50);

        btkelolamobil.setBackground(new java.awt.Color(255, 153, 153));
        btkelolamobil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btkelolamobil.setForeground(new java.awt.Color(255, 255, 255));
        btkelolamobil.setText("Kelola Data Mobil");
        btkelolamobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkelolamobilActionPerformed(evt);
            }
        });
        getContentPane().add(btkelolamobil);
        btkelolamobil.setBounds(20, 320, 210, 50);

        btkelolatransaksi.setBackground(new java.awt.Color(255, 153, 153));
        btkelolatransaksi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btkelolatransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btkelolatransaksi.setText("Kelola Data Transaksi");
        btkelolatransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkelolatransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btkelolatransaksi);
        btkelolatransaksi.setBounds(20, 490, 210, 50);

        btkeluar.setBackground(new java.awt.Color(255, 0, 0));
        btkeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btkeluar.setForeground(new java.awt.Color(255, 255, 255));
        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btkeluar);
        btkeluar.setBounds(1100, 10, 70, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Entity/bg2_1.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1280, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtnohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnohpActionPerformed

    private void txtpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        PreparedStatement preparedStatement = null;
        String nik = txtnik.getText();
        try {
            Connection connection = Koneksi.getConnection();
            System.out.println("Database connected successfully!");

            String query = "DELETE FROM tbuser WHERE NIK ='" + nik + "'";
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.executeUpdate();
            tampiltabel();
            System.out.println("Data dihapus");

        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            if (preparedStatement != null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        PreparedStatement preparedStatement = null;
        try {
            Connection connection = Koneksi.getConnection();
            System.out.println("Database connected successfully!");

            String query = "INSERT INTO tbuser (NIK, namaUser, nohpUser, passwordUser) VALUES (?,?, ?, ?)";
            preparedStatement = connection.prepareStatement(query);

            preparedStatement.setString(1, txtnik.getText());
            preparedStatement.setString(2, txtnama.getText());
            preparedStatement.setString(3, txtnohp.getText());
            preparedStatement.setString(4, new String(txtpw.getPassword()));

            int rowsInserted = preparedStatement.executeUpdate();
            tampiltabel();
            System.out.println("Rows inserted: " + rowsInserted);

            if (rowsInserted > 0) {
                System.out.println("Data berhasil ditambahkan ke tabel user.");
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            if (preparedStatement != null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_bttambahActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        String nik = txtnik.getText();
        String nama = txtnama.getText();
        String hp = txtnohp.getText();
        String pass = new String(txtpw.getPassword());

        PreparedStatement preparedStatement = null;
        try {
            Connection connection = Koneksi.getConnection();
            System.out.println("Database connected successfully!");

            String query = "UPDATE tbuser "
                    + "SET namaUser='" + nama + "',nohpUser='" + hp + "',passwordUser ='" + pass + "' WHERE NIK= '" + nik + "'";
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.executeUpdate();
            tampiltabel();
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            if (preparedStatement != null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_bteditActionPerformed

    private void btkelolauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkelolauserActionPerformed

    }//GEN-LAST:event_btkelolauserActionPerformed

    private void btkelolamobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkelolamobilActionPerformed
        CarManagement user = new CarManagement();
        user.setSize(1181, 700);
        user.setResizable(false);
        user.setVisible(true);
        user.setExtendedState(JFrame.NORMAL);
        this.dispose();
    }//GEN-LAST:event_btkelolamobilActionPerformed

    private void btkelolatransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkelolatransaksiActionPerformed
        TransactionManagement tm = new TransactionManagement();
        tm.setSize(1181, 700);
        tm.setResizable(false);
        tm.setVisible(true);
        tm.setExtendedState(JFrame.NORMAL);
        this.dispose();
    }//GEN-LAST:event_btkelolatransaksiActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
        LandingPage lp = new LandingPage();
        lp.setSize(1181, 700);
        lp.setResizable(false);
        lp.setVisible(true);
        lp.setExtendedState(JFrame.NORMAL);
        this.dispose();
    }//GEN-LAST:event_btkeluarActionPerformed

    public void addUser(String nik, String nama, String noHp, String password) {
        DefaultTableModel model = (DefaultTableModel) TableUser.getModel();
        model.addRow(new Object[]{nik, nama, noHp, password});
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NIK;
    private javax.swing.JTable TableUser;
    private javax.swing.JLabel background;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkelolamobil;
    private javax.swing.JButton btkelolatransaksi;
    private javax.swing.JButton btkelolauser;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton bttambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nohp;
    private javax.swing.JLabel password;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JPasswordField txtpw;
    // End of variables declaration//GEN-END:variables
}
